### ISSUE TITLE
Question: can the tuplex compiler be repurposed by other python packages like dask?

### ISSUE THREAD

**Issue by xiaodaigh** [tuplex/tuplex#12]
Apologies in advance if this is not the right forum to ask questions. But I couldn't find anything on the docs.

Theoretically, can the Dask folks take parts of your compiler and fit them into their framework so they get some speed up for the compiled to native part as well?

**Comment by ms705** [comment]
While Dask could adopt Tuplex's code generation for individual operations (at some engineering effort), the result probably wouldn't be as fast as Tuplex's end-to-end optimized pipelines. Tuplex avoids the overheads of Python object format and optimizes across operators; I expect a major Dask rewrite would be needed to match this.
