### ISSUE TITLE
Support for Python 3.10 / 3.11?

### ISSUE THREAD

**Issue by ecederstrand** [tuplex/tuplex#137]
PyPI only has wheels for Python 3.7-3.9. Would it be possible to publish wheels for newer versions?

**Comment by ecederstrand** [comment]
Ping @LeonhardFS ?

**Comment by LeonhardFS** [comment]
Hi Erik,

we just published new wheels for Python 3.8 - 3.11 including Apple Silicon support for Python 3.9 - 3.11. Closing this issue for now with the release, if you encounter any problems please let us know and we'll do our best to address them swiftly.
