### ISSUE TITLE
Tuplex crashes kernel on first startup [MacOS/docker]

### ISSUE THREAD

**Issue by niviksha** [tuplex/tuplex#3]
First, congrats on tuplex, super excited to dive in 

By way of background - till recently, I was head of Product at OmniSci where we were solving similar problems in large scale data science and came up with our own way (in conjunction with our partners Quansight) to leverage our existing SQL query compiler pipeline (LLVM-based) in OmniSciDB to allow analysts to [author python-based UDFs and UDTFs](https://summit.omnisci.com/live-sessions/user-defined-algorithms-on-big-data-with-omnisci) and register the resulting LLVM IR at runtime with the rest of the query compilation workflow. Slightly different motivations (i.e runtime UDFs/UDTFs that can be used within SQL) than for data science, but many similar problems.

On a more mundane note, I tried using the docker/Mac install (Catalina 10.15.7, Docker Mac) - when I run the cell to initialize the tuplex context, the python kernel always restarts and I cant proceed any further. The notebook logs in the console dont reveal too much either, and the log.txt I see is blank.

Any pointers on what I should be looking for?

**Comment by LeonhardFS** [comment]
Thanks for bringing this to our attention and your interest in the project!
The segfault due to missing AWS credentials should have been fixed in the v0.3.1 release.

If the pip package doesn't work, it's also always possible to build Tuplex from scratch. The simplest way is to use the following command sequence for Mac OS:

```
brew install llvm@9 boost boost-python3 aws-sdk-cpp pcre2 antlr4-cpp-runtime googletest gflags yaml-cpp celero
python3 -m pip cloudpickle numpy
python3 setup.py install

cd tuplex
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make # use make -j<n-threads>

# a python package will be in dist/python
cd dist/python
python3 setup.py develop # or use python3 setup.py install --user
```
