### ISSUE TITLE
SegFault after `c = Context()`

### ISSUE THREAD

**Issue by rickhg12hs** [tuplex/tuplex#4]
After installing in a `venv` with:
```bash
python -m pip install --upgrade --upgrade-strategy eager tuplex
```
... and attempting the first example:
```python
python
from tuplex import *
Welcome to

  _____            _
 |_   _|   _ _ __ | | _____  __
   | || | | | '_ \| |/ _ \ \/ /
   | || |_| | |_) | |  __/>  <
   |_| \__,_| .__/|_|\___/_/\_\ 0.3.0
            |_|
    
using Python 3.8.10 (default, May  4 2021, 00:00:00) 
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
 Interactive Shell mode
>>> c = Context()
Segmentation fault (core dumped)
```

**Comment by rickhg12hs** [comment]
Thanks!  It seems to be running properly now.

I'm wondering, is the performance penalty very high using the package from PyPi versus building from source?

**Comment by LeonhardFS** [comment]
This is a great question!

We haven't run an experiment comparing the Pypi version built using the `tuplex/ci` image based on [manylinux](https://github.com/tuplex/tuplex/blob/master/scripts/docker/ci/Dockerfile) vs. Tuplex built for a specific hardware configuration yet. I'd suspect that potentially building Tuplex + dependencies using `native` might be faster than the pip-package. Yet, the LLVM IR emitted by the UDF/Query-compiler will always optimize for the architecture it's run on. Therefore, any speed differences should be only attributable to the runtime (stored in `tuplex/libexec/tuplex_runtime.so` -> can be swapped out with one using different compiler flags, i.e. this is a setting in the Context object) or functions used from dependencies. Potentially also the compilation/planning logic, which is written in C++ may be affected by different compiler flags.
