### ISSUE TITLE
[BUG] File output deletes working directory

### ISSUE THREAD

**Issue by bgivertz** [tuplex/tuplex#58]
Found a very severe bug, be careful when testing as it will erase the entire directory that tuplex is running from.

The following examples cause tuplex to crash and delete the entire working directory:
```python3
c.pararllelize([1, 2, 3]).tocsv(".")
c.parallelize([1, 2, 3]).toorc(".")
```

**Comment by LeonhardFS** [comment]
hm maybe we should add a check which prevents specifiying the current working directory + any parent directory as output?
