### ISSUE TITLE
[BUG] Error when importing tuplex 0.3.1

### ISSUE THREAD

**Issue by yannisfoufoulas** [tuplex/tuplex#60]
Hi, I am getting an "Illegal instruction (core dumped)" error when importing tuplex
My CPU is Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz

This happens if a install tuplex with pip install and also with docker installation

Edit: It seems that the problem is that this CPU does not support AVX2 instructions (it supports AVX), is there any way to run tuplex without AVX2?

**Comment by LeonhardFS** [comment]
Indeed we had in our original CMake a too aggressive optimization scheme using -march=native enabled. This resulted in requiring AVX2 instructions. In PR #31 [https://github.com/tuplex/tuplex/pull/31](https://github.com/tuplex/tuplex/commit/03733a57ccb5a3770eecaf1c3adcfb520ed82138) this has been resolved. We're planning on publishing a new release within the next days/weeks to avoid the illegal instruction error when installing from pip. Unfortunately, there's no way to update an already released version on pypi.org - it can be only yanked.

In the meantime, if you like to try out Tuplex please check out the current master. `./scripts/build_wheel_linux.sh` allows to build a Linux-compatible wheel which can be simply installed via `pip install <whl file>`. Alternatively, if you have the prerequisites installed you can also create a local version using `python3 setup.py develop --user` or via `python3 setup.py install --user`.
